server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes: []   # пока пусто, чтобы без сервисов запускалось

  redis:
    host: redis
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/demo

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway